# Generated by Django 4.2.5 on 2023-09-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedtasks',
            options={'verbose_name': 'SolvedTasks', 'verbose_name_plural': 'SolvedTasks'},
        ),
        migrations.AlterModelOptions(
            name='taskkeys',
            options={'verbose_name': 'TaskKeys', 'verbose_name_plural': 'TaskKeys'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tasks', 'verbose_name_plural': 'Tasks'},
        ),
    ]
